msp-strawberry-core:
  state-dir: persistence/core

spring:
  application:
    name: strawberry-core
  datasource:
    url: jdbc:h2:file:/Users/dmitrijusatenko/IdeaProjects/stawberry-app-msp/persistence/core/tokenstore;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true

server:
  port : 8081
