msp-strawberry-read:
  prisma-url: http://localhost:4466/

server:
  port : 8081

#H2 settings
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/strawberry
    username: sa
    password:
    driverClassName: org.h2.Driver